import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { CarModel, CarVariant } from '../models/car.model';

@Injectable({
  providedIn: 'root'
})
export class CarService {
  private models: CarModel[] = [
    {
      id: '1',
      name: 'ERTIGA',
      description: 'The new Ertiga is designed to inspire envy with its bold design and sophisticated style.',
      imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
      variants: [
        {
          id: '1-1',
          name: 'LXI',
          exShowroomPrice: 862710,
          rto: 80017,
          insurance: 25266,
          tcs: 8627,
          extendedWarranty: 14237,
          ccp: 1322,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'Petrol',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-2',
          name: 'VXI',
          exShowroomPrice: 962710,
          rto: 90017,
          insurance: 28266,
          tcs: 9627,
          extendedWarranty: 16237,
          ccp: 1522,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'Petrol',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-3',
          name: 'VXI (O)',
          exShowroomPrice: 1057710,
          rto: 121171,
          insurance: 30313,
          tcs: 10577,
          extendedWarranty: 17842,
          ccp: 1853,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'Petrol',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-4',
          name: 'ZXI',
          exShowroomPrice: 1072710,
          rto: 122671,
          insurance: 29841,
          tcs: 10727,
          extendedWarranty: 19612,
          ccp: 1699,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'Petrol',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-5',
          name: 'ZXI (O)',
          exShowroomPrice: 1167710,
          rto: 132171,
          insurance: 31938,
          tcs: 11677,
          extendedWarranty: 19718,
          ccp: 1853,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'Petrol',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-6',
          name: 'VXI CNG',
          exShowroomPrice: 1057710,
          rto: 121171,
          insurance: 30313,
          tcs: 10577,
          extendedWarranty: 17842,
          ccp: 1853,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'CNG',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-7',
          name: 'VXI CNG (O)',
          exShowroomPrice: 1167710,
          rto: 132171,
          insurance: 31938,
          tcs: 11677,
          extendedWarranty: 19718,
          ccp: 1853,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'CNG',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-8',
          name: 'ZXI CNG',
          exShowroomPrice: 1267710,
          rto: 142171,
          insurance: 32938,
          tcs: 12677,
          extendedWarranty: 20718,
          ccp: 1953,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'CNG',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-9',
          name: 'ZXI CNG (O)',
          exShowroomPrice: 1367710,
          rto: 152171,
          insurance: 33938,
          tcs: 13677,
          extendedWarranty: 21718,
          ccp: 2053,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'CNG',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        },
        {
          id: '1-10',
          name: 'ZXI+ CNG',
          exShowroomPrice: 1467710,
          rto: 162171,
          insurance: 34938,
          tcs: 14677,
          extendedWarranty: 22718,
          ccp: 2153,
          accessories: 45000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/ertiga-new/ertiga_profile.webp',
          rating: 4.7,
          reviews: 81,
          transmission: 'Manual',
          engine: '998 cc',
          fuelType: 'CNG',
          power: '114 bhp',
          bootSpace: '446 Litres',
          airbags: 6
        }
      ]
    },
    {
      id: '2',
      name: 'SWIFT',
      description: 'The Swift is a sporty, stylish and fun to drive hatchback that perfectly reflects your personality.',
      imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
      variants: [
        {
          id: '2-1',
          name: 'LXI',
          exShowroomPrice: 549000,
          rto: 55000,
          insurance: 18000,
          tcs: 5490,
          extendedWarranty: 12000,
          ccp: 1200,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-2',
          name: 'VXI',
          exShowroomPrice: 632000,
          rto: 63200,
          insurance: 20000,
          tcs: 6320,
          extendedWarranty: 13000,
          ccp: 1300,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-3',
          name: 'VXI AMT',
          exShowroomPrice: 682000,
          rto: 68200,
          insurance: 21000,
          tcs: 6820,
          extendedWarranty: 13500,
          ccp: 1350,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'AMT',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-4',
          name: 'ZXI',
          exShowroomPrice: 699000,
          rto: 69900,
          insurance: 22000,
          tcs: 6990,
          extendedWarranty: 14000,
          ccp: 1400,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-5',
          name: 'ZXI AMT',
          exShowroomPrice: 749000,
          rto: 74900,
          insurance: 23000,
          tcs: 7490,
          extendedWarranty: 14500,
          ccp: 1450,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'AMT',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-6',
          name: 'ZXI+',
          exShowroomPrice: 789000,
          rto: 78900,
          insurance: 24000,
          tcs: 7890,
          extendedWarranty: 15000,
          ccp: 1500,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-7',
          name: 'ZXI+ AMT',
          exShowroomPrice: 839000,
          rto: 83900,
          insurance: 25000,
          tcs: 8390,
          extendedWarranty: 15500,
          ccp: 1550,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'AMT',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-8',
          name: 'ZXI+ DT',
          exShowroomPrice: 799000,
          rto: 79900,
          insurance: 24500,
          tcs: 7990,
          extendedWarranty: 15250,
          ccp: 1525,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-9',
          name: 'ZXI+ DT AMT',
          exShowroomPrice: 849000,
          rto: 84900,
          insurance: 25500,
          tcs: 8490,
          extendedWarranty: 15750,
          ccp: 1575,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'AMT',
          engine: '1197 cc',
          fuelType: 'Petrol',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        },
        {
          id: '2-10',
          name: 'ZXI+ CNG',
          exShowroomPrice: 889000,
          rto: 88900,
          insurance: 26500,
          tcs: 8890,
          extendedWarranty: 16250,
          ccp: 1625,
          accessories: 25000,
          rewardProgram: 885,
          fastag: 600,
          imageUrl: 'https://marutisuzukiarenaprodcdn.azureedge.net/-/media/images/maruti/marutisuzuki/car/car-profile-shots/swift-launch-2021/swift-profile.webp',
          rating: 4.5,
          reviews: 120,
          transmission: 'Manual',
          engine: '1197 cc',
          fuelType: 'CNG',
          power: '89 bhp',
          bootSpace: '268 Litres',
          airbags: 2
        }
      ]
    }
  ];
  
  private modelsSubject = new BehaviorSubject<CarModel[]>(this.models);

  getModels(): Observable<CarModel[]> {
    return this.modelsSubject.asObservable();
  }

  addModel(model: CarModel) {
    this.models.push(model);
    this.modelsSubject.next([...this.models]);
  }

  addVariant(modelId: string, variant: CarVariant) {
    const model = this.models.find(m => m.id === modelId);
    if (model) {
      model.variants.push(variant);
      this.modelsSubject.next([...this.models]);
    }
  }

  getModelById(id: string): CarModel | undefined {
    return this.models.find(m => m.id === id);
  }
}